[project]
name = "focusnfe"
version = "0.1.0"
description = "A robust, type-safe Python library for interacting with FocusNFe services."
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "Bjorn Boschman", email = "bjorn.boschman@admdoctor.com.br" }
]
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.12.5",
    "requests>=2.32.5",
]

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "requests-mock>=1.12.1",
    "ruff>=0.14.10",
]

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "U"]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
